nginx/nginx-prometheus-exporter

README.md
exporter.go

Adding a flag to allow connecting to insecure TLS endpoints 
- [ x ] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-prometheus-exporter/blob/master/CONTRIBUTING.md) guide
- [ x ] I have proven my fix is effective or that my feature works
- [ x ] I have checked that all unit tests pass after adding my changes
- [ x ] I have ensured the README is up to date
- [ x ] I have rebased my branch onto master
- [ x ] I will ensure my PR is targeting the master branch and pulling from my branch on my own fork

add option to skip tls verify

---

README.md
collector/nginx_plus.go

Closes: https://github.com/nginxinc/nginx-prometheus-exporter/pull/1
* Add Stream upstream metrics
* Add Stream Server Zone metrics
* Add Stream Server metrics
* Update documentation to include stream documentation

Add stream metrics support

---

Makefile

Adding a stage to build prometheus exporter binaries for the
supported platforms: Linux (i386 and amd64)
Makefile has now targes to build binaries for i386 and amd64 (linux).
Cleanup and build binary of local system targets added too.

Add binaries build to Makefile. Add clean target.

---

README.md
collector/helper.go
collector/nginx.go
collector/nginx_plus.go
exporter.go

- Implements https://github.com/nginxinc/nginx-prometheus-exporter/issues/26 - nginx_up and nginxplus_up metrics.
- Adds -nginx.timeout cli argument for setting a timeout for scrapping metrics from NGINX or NGINX Plus.

Implement up metrics and timeout cli argument

---

README.md
exporter.go

Add nginxexporter_build_info metric
Implements https://github.com/nginxinc/nginx-prometheus-exporter/issues/28 suggestion No 1

Add nginxexporter_build_info metric

---

README.md
client/nginx.go
exporter.go
exporter_test.go

Closes: https://github.com/nginxinc/nginx-prometheus-exporter/issues/36
The exporter will now retry to connect to NGINX if it is unreachable, and `nginx.retries` is set. It will retry a number of times which is set via the new `nginx.retries` cli arg or `NGINX_RETRIES` shell variable.
* Add `nginx.retries` and `nginx.retry-interval` cli args
* Add `NGINX_RETRIES`, `NGINX_RETRY_INTERVAL` and `TIMEOUT` shell variables
* Add NGINX Prometheus Exporter started log. - This lets you know that a retry has succeeded. 
* Add SIGTERM signal handler. - This causes the exporter to exit gracefully once a SIGTERM is received.
* Update README with new cli args/shell variables
* Add unit test for creating a Nginx/Nginx Plus client

Retry connection if NGINX unavailable

---

exporter.go
exporter_test.go

`$ go run exporter.go -nginx.retries -1`
Catch error and return it.
Exits in non graceful manner.
```
panic: interface conversion: interface {} is nil, not *client.NginxClient
goroutine 1 [running]:
main.main()
/go/src/github.com/nginxinc/nginx-prometheus-exporter/exporter.go:167 +0xb11
```
```
invalid value "-1" for flag -nginx.retries: parse error
Usage of ./nginx-prometheus-exporter:
-nginx.plus
Start the exporter for NGINX Plus. By default, the exporter is started for NGINX. The default value can be overwritten by NGINX_PLUS environment variable.
-nginx.retries uint
A number of retries the exporter will make on start to connect to the NGINX stub_status page/NGINX Plus API before exiting with an error. The default value can be overwritten by NGINX_RETRIES environment variable. …
```

Fix nginxRetries accepts a negative value

---

exporter.go

The exporter does not sleep in between the first connection attempt and the first retry attempt.
Introduced in: https://github.com/nginxinc/nginx-prometheus-exporter/commit/b499ca793a540113d9690c035af4756544a24d2b
BEFORE fix(with additional debug logs for clarity)
```
$ ./nginx-prometheus-exporter -nginx.scrape-uri=wrong.nginx.com -nginx.retries=7 -nginx.retry-interval=5s
2019/04/08 16:31:18 Starting NGINX Prometheus Exporter Version=0.3.0 GitCommit=d35d429
2019/04/08 16:31:18 TRY
2019/04/08 16:31:18 RETRY 1
2019/04/08 16:31:18 Could not create Nginx Client. Retrying in 5s...
2019/04/08 16:31:23 RETRY 2
2019/04/08 16:31:23 Could not create Nginx Client. Retrying in 5s...
```
AFTER fix(with additional debug logs)
```
$ ./nginx-prometheus-exporter -nginx.scrape-uri=wrong.nginx.com …
```

Fix sleep for first retry

---

collector/nginx_plus.go
go.mod
go.sum
vendor/github.com/nginxinc/nginx-plus-go-client/client/nginx.go
vendor/modules.txt

* If zone sync metrics are not present (`nil`) do not expose them, for consistency.

Do not expose zone sync metric if not present

---

go.mod
go.sum
vendor/github.com/nginxinc/nginx-plus-go-client/client/nginx.go
vendor/modules.txt

Session `4xx` and `5xx` metrics were fixed in https://github.com/nginxinc/nginx-plus-go-client/commit/f8b65d22607173ddb02eaef76833ea4f7658572b. 
This PR updates that dependency to that commit in order to fix the issue.
* The exporter would not scrape this values correctly and would always report the metrics as `0`.
* The exporter correctly scrapes and exports these metrics.

Fix stream server zones session metrics

---

CHANGELOG.md
Makefile
README.md

* [60](https://github.com/nginxinc/nginx-prometheus-exporter/pull/60): *Fix session metrics for stream server zones*. Session metrics with a status of `4xx` or `5xx` are now correctly reported. Previously they were always reported as `0`.

Release 0.4.2

---

.travis.yml
Dockerfile
go.mod

Go 1.13 was released recently.
We need to update our projects to use Go 1.13
Make sure both travis files (if present) and Makefiles are updated.

Update Go version to 1.13

---

README.md
collector/nginx_plus.go

Location zone and resolver metric support

---

grafana/dashboard.json

Fixes #69
Before, each panel assumed the default Datasource. If Prometheus was not the default datasource the data was not correct.
With this, we force that all panels need to have the same value as the variable `${DS_PROMETHEUS}` which is set when importing the panel.

Do not assume default datasource in Grafana panels

---

README.md
exporter.go
exporter_test.go

Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>
Add ability to scrape and listen on unix domain socket.  
nginx.conf example for scraping:
```
http {
access_log off;
server {
server_name _;
listen unix:/etc/sockets/status.sock;
location /nginx_status {
stub_status on;
}
}
}
```

Add ability to scrape and listen unix domain sockets

---

collector/nginx_plus.go

Fixed a type-o in the metric help text/description.

Fix type-o

---

collector/helper.go
collector/nginx.go
collector/nginx_plus.go

Related to [Issue 95](https://github.com/nginxinc/nginx-prometheus-exporter/issues/95)

Add const labels to upMetric

---

README.md
exporter.go

Implemented options to specify:
* a client certificate (and key) in *PEM* format to authenticate against the server
* a CA certificate in *PEM* format to authenticate the server

Implemented TLS client certificate authentication

---

exporter.go

The HTML on the `/` path show an hardcoded value for the metrics path. This fixes it.

exporter: link to actual metricsPath

---

build/Dockerfile

* Add USER statement to run as non-root user
* Move to gcr.io/distroless/static image
**UPDATE:**
- Use `gcr.io/distroless/static` image
- Removed user creation
- Set `USER 1001:1001` in `Dockerfile`
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
Fixes #102 
https://github.com/nginxinc/nginx-prometheus-exporter/issues/102

Move to non-root container

---

grafana/dashboard.json

When using this Grafana dashboard, we get the following error: `Datasource named ${DS_PROMETHEUS} was not found`. This change fixes this issue.
- [ X ] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-prometheus-exporter/blob/master/CONTRIBUTING.md) guide
- [ X ] I have proven my fix is effective or that my feature works
- [ X ] I have checked that all unit tests pass after adding my changes
- [ X ] I have ensured the README is up to date
- [ X ] I have rebased my branch onto master
- [ X ] I will ensure my PR is targeting the master branch and pulling from my branch on my own fork

Fix default prometheus datasource was not found error

---

collector/nginx_plus.go
exporter.go

Add optional support to add variable labels to Upstream Server and Server Zone metrics when using the prom exporter as a library.
This change does not affect when the exporter is run as a binary, it's basically a change needed by the Ingress Controller when using this code, to make sure we can create relations between Ingress Controller resources and NGINX configuration to add labels to the metrics.

Add variable labels to Upstream Servers and Server Zones metrics

---

collector/nginx_plus.go
exporter.go

Add support for `pod_labels` when using the prom exporter as a library 

Extend Upstream Servers with pod_name label

---

.github/workflows/ci.yml

Update Docker Action to v2, add Docker layer caching, parallelize unit tests

Update docker action

---

Makefile

The official prometheus exporters use all the same naming scheme. You used a `-` instead of a `.` for whatever reason.
To make it easier to download exporters, in standardized ways, it would be good if everyone follows this schema.

Use same style of release names as official exporters

---

README.md
exporter.go

Add a new flag `version` to display the current version. This is useful to check if the exporter needs an update without trying to launch the exporter.

Add version cli argument

---

collector/nginx_plus.go
exporter.go

Add k8s object labels to tcp metrics

Add k8s object labels to tcp metrics

---

README.md
exporter.go

As some high secured environments should have tls comms even for metrics, this PR address to close that gap and makes serve metrics using https an option.

add tls support

---

README.md

This should help prevent confusion like in this issue https://github.com/nginxinc/nginx-prometheus-exporter/issues/153 , where no '=' was used for the value of a boolean arg. For boolean args, it is necessary to use '=': 
* -nginx.ssl-verify=false - correct
* -nginx.ssl-verify - correct
* -nginx.ssl-verify false - incorrect

Use equal sign in cli args examples

---

.github/workflows/ci.yml
.gitignore
.goreleaser.yml
Makefile
build/Dockerfile
exporter.go
go.sum

- Added GoReleaser configuration and add step in CI to automatically build and publish binaries on the creation of a new tag.
- Added new variable `date` (passed by GoReleaser).
- Added missing variables in Docker image pushed by CI.
- Added binaries for ARM.

Add GoReleaser and fix missing vars in CI workflow

---

.github/workflows/ci.yml
.goreleaser.yml
Makefile
build/Dockerfile

- Building binaries for more versions of arm, 386, ppc64le, mips64le and s390x
- Building docker images for ARM and ppc64 (other platforms are not supported by distroless docker image)

Add support for more platforms, push to Docker Hub

---

.github/workflows/ci.yml
build/Dockerfile

Support building docker images for mips64le and 386

Use scratch to support building for more archs

---

.goreleaser.yml
Makefile
build/Dockerfile
client/nginx.go
exporter.go

Refactor for go 1.16.     ( Related PR: https://github.com/nginxinc/nginx-prometheus-exporter/pull/160 )
I fixed 2 points.
1. Replace `io/ioutil` with `io` or `os`.
`io/ioutil` is "deprecated", so I replace with `io` or `os`.
ref: https://golang.org/doc/go1.16#ioutil
`io/ioutil` is unlikely to be deleted, but `io` or `os` is better.
ref: https://twitter.com/_rsc/status/1351676094664110082
2.  Remove `GO111MODULE=on`
Default value of `GO111MODULE` is `on` from go 1.16.
So we no longer have to set this each time.
ref: https://golang.org/doc/go1.16#modules

Refactor for go 1.16

---

.golangci.yml
exporter.go

Adding `revive` (replacement for the deprecated `golint`) with the [recommended](https://github.com/mgechev/revive#recommended-configuration) configuration

Add revive linter with recommended config

---

.github/workflows/ci.yml
.goreleaser.yml
Makefile

Add binaries for MacOS
Closes #178

Add binaries for macOS

---

.github/workflows/ci.yml

- Use the same job for PRs/edge/nightly/release 
- Add images for `edge` and `nightly`
- Add labels to the Docker image

Simplify CI workflow, add edge and nightly

---

build/Dockerfile

From the docs https://github.com/moby/buildkit/blob/dockerfile/1.4.0/frontend/dockerfile/docs/syntax.md#linked-copies-copy---link-add---link
>Enabling this flag in `COPY` or `ADD` commands allows you to copy files with enhanced semantics where your files remain independent on their own layer and don't get invalidated when commands on previous layers are changed.

Use linked copies in Dockerfile

---

.github/workflows/dependabot-auto-merge.yml

Enables auto-merge. The PR will only be merged after the checks are satisfied.

Add workflow to enable auto-merge for dependabot

---

.github/workflows/ci.yml
Makefile
build/Dockerfile
exporter.go

With Go 1.18 it's possible to get `git` info from the binary, removing the need to inject values at build time.

Read Go build info from the binary

---

exporter.go

Adds timeout to fix 
`G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)`

Add ReadHeaderTimeout to http.Server

---

README.md
collector/nginx_plus.go

Adds metrics for:
- HTTP Requests Rate Limiting
- HTTP Connections Limiting
- Stream Connections Limiting
Closes #280

Add metrics from NGINX Plus API version 6

---

README.md
collector/nginx_plus.go

Adds metrics for the codes data in responses for each HTTP upstream, server zone, and location zone.
Closes #220

Add metrics from NGINX Plus API version 7

---

README.md
collector/nginx_plus.go

Adds metrics for the ssl data for each HTTP upstream, server zone, and stream upstream, server zone.
Closes #284

Add metrics from NGINX Plus API version 8

---

README.md
collector/nginx_plus.go

Remove a duplicate "that were" in metric description
While adding metrics from the README to our grafana dashboards I found a small error in the description. This fixes just that.

Fix typographical error

---

.github/labeler.yml
.github/release-drafter.yml
.github/workflows/labeler.yml
.github/workflows/release-drafter.yml

Uses the official `actions/labeler` even if with a new feature not yet merged that can use branch names.
The action can now label PRs coming from forks and has only the required permission to manage the labels.
This is the first step towards removing release-drafter.

Replace autolabeler with `actions/labeler`

---

.github/workflows/ci.yml
.github/workflows/dependabot-auto-merge.yml
.github/workflows/dockerhub-description.yml
.github/workflows/fossa.yml
.github/workflows/lint.yml
.github/workflows/notifications.yml
.github/workflows/release-drafter.yml
.github/workflows/stale.yml

Updates the runners to the latest ubuntu https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

Update GitHub Actions runners to Ubuntu 22.04

---

.github/workflows/ci.yml
.github/workflows/lint.yml

Resolve  #367 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=go_path::$(go env GOPATH)"
```
```yml
run: echo "::set-output name=go_version::$(grep "go 1." go.mod | cut -d " " -f 2)")
```
**TO-BE**
```yml
echo "go_path=$(go env GOPATH)" >> $GITHUB_OUTPUT
```
```yml
run: echo "go_version=$(grep "go 1." go.mod …
```

Replace deprecated command with environment file

---

.github/workflows/ci.yml
README.md
build/Dockerfile

Adds SBOM for the Docker images.

Add SBOMs for Docker images

---

.github/workflows/ci.yml

This PR updates the workflows to use OIDC to log in to AWS using short-lived tokens instead of static keys.
From the docs:
> OpenID Connect (OIDC) allows your GitHub Actions workflows to access resources in Amazon Web Services (AWS), without needing to store the AWS credentials as long-lived GitHub secrets.

Use OIDC to login to AWS

---

.github/workflows/ci.yml

The action needs write permission to be able to create/update a release draft.

Fix permissions for CI workflow

---

exporter.go

Converts old flag format to new format and warns users instead of erroring out.
Closes #447

Deprecate old flag format

---

README.md
collector/nginx_plus.go
exporter.go

Fixes #522 and exposes cache metrics from NGINX Plus API.
guide

add cache metrics for NGINX plus

---

README.md
collector/nginx_plus.go
exporter.go

˜### Proposed changes
Add metrics for NGINX worker data, connection accepted, dropped, current active, current idle, http request total and current.
Example NGINX Plus API response /workers/
```
[
{
"id": 0,
"pid": 970577,
"connections": {
"accepted": 12364048,
"dropped": 0,
"active": 1,
"idle": 80
},
"http": {
"requests": {
"total": 21726744,
"current": 0
}
}
},
{
"id": 1,
"pid": 970578,
"connections": {
"accepted": 13538199,
"dropped": 0,
"active": 2,
"idle": 66
},
"http": {
"requests": {
"total": 22635133,
"current": 1
}
}
}
]
```
Prometheus metrics for workers
```
nginxplus_worker_connection_accepted{id="0",pid="970577"} 1.2363957e+07
nginxplus_worker_connection_accepted{id="1",pid="970578"} 1.3538027e+07
nginxplus_worker_connection_active{id="0",pid="970577"} 2 …
```

Add metrics from NGINX Plus API version 9

---

README.md
exporter.go

Make the `nginx.scrape-uri` accept a slice of addresses, and register prometheus collectors for each monitored nginx instance.
This revision came out of a discussion in https://github.com/nginxinc/nginx-prometheus-exporter/issues/229. The general concensus by those in the thread was that it would be better to run an nginx-exporter for every monitored nginx instance. I had implemented these changes for my own use, so I decided to make them available to the wider community here.
Feel free to merge, or don't :-) I'm fine with either.
guide

Add support for multiple scrape addresses

---

.goreleaser.yml

`tap` is deprecated and `repository` should be used.

Replace deprecated value in GoReleaser

---

.github/workflows/ci.yml
CHANGELOG.md
Makefile
README.md
exporter.go

Release 1.0.0

---

.github/workflows/ci.yml

GoReleaser can't close milestones on release because it doesn't have the right permissions. This adds the right permissions.

Set permissions to close milestones for GoReleaser

---

.goreleaser.yml

Fix GoReleaser config

---

Makefile

This pull request resolves #620.
In the Makefile, the `help` and `nginx-prometheus-exporter` targets have been swapped, now making `nginx-prometheus-exporter` the default target again. This adjusts the default build command ensuring consistency with the instructions in `README.md`.
Please provide feedback if further changes are needed.

Restore the old behavior when 'nginx-prometheus-exporter' was the default rule for make

---

.github/labeler.yml
.github/workflows/lint.yml
.github/workflows/scorecards.yml
.golangci.yml
.pre-commit-config.yaml
.yamllint.yaml

Adds `yamllint` and fixes files
Closes #601

Add yamllint

---

.github/workflows/lint.yml
.golangci.yml
.pre-commit-config.yaml
client/nginx.go
collector/helper_test.go
collector/nginx.go
collector/nginx_plus.go
exporter.go
exporter_test.go

Enables new linters and changes the code to fix the problems.
The main change is fieldalignment that should result in performance improvements.

Enable more linters

---

collector/nginx_plus.go

Turn down logging when upstream labels are empty.
guide

switch from warning to debug when upstream labels are empty

---

.github/PULL_REQUEST_TEMPLATE.md
.golangci.yml
collector/nginx_plus.go
exporter.go
exporter_test.go

Adds more linters and fixes errors
guide

Add more linters

---

README.md

Updated Live Monitoring link to point to the feature in the docs page, as the previous page has gone missing.

Update Live Monitoring link

---

.github/workflows/f5-cla.yml
CONTRIBUTING.md

An updated version of #661 that includes a GitHub action workflow integrating the F5 CLA into the typical GitHub pull-request flow for individual contributors.
As part of this workflow's configuration, the following usernames were marked as F5 maintainers:
* `lucacome`
* `pleshakov` 

Add GitHub Action workflow for F5 CLA integration

---

README.md
collector/nginx_plus.go
exporter.go

Variable labels are not needed for workers since there's no extra information that can be attached to them.

Remove unnecessary variable labels for workers

---

.golangci.yml
collector/nginx_plus.go

Adds linters that check for bugs and fixes errors.
See first commit for the errors.

Add linters that check for bugs

---

collector/nginx_plus.go

Caches were not using the variable labels.

Fix Cache to use variable labels

---

collector/nginx_plus.go

This reverts commit d3f9f94934c8a90de58ca264ee531a7648b2bb2b.
The commit changed the level for all labels and not just upstream, but in any case, we don't want to suppress the warnings, we want to notify the user of the library that the labels are not configured correctly.
If for some reason the warning wants to be ignored, it's always possible to set the level on the client side.

Revert "switch from warning to debug when upstream labels are empty (#724)"

---

examples/systemd/README.md

Add "Steps to add users"
Closes #799
---
**Just a documentation update, validation code and test cases?**

Update  NGINX Prometheus Exporter with systemd-activated socket

---

.github/workflows/ci.yml
.golangci.yml
.goreleaser.yml
Makefile
collector/helper_test.go
collector/nginx.go
collector/nginx_plus.go
exporter.go
exporter_test.go
go.mod
go.sum

After https://github.com/prometheus/exporter-toolkit/pull/240 we can switch to using slog.
Closes #484

Switch to slog

---

.github/workflows/ci.yml
.goreleaser.yml
build/Dockerfile

Debian builds packages for `ppc64` and  `riscv64`. Alpine supports `mips64`.
NGINX runs on `freebsd` and `solaris`.
This PR adds support for all those architectures and platforms.
It also adds docker builds for all variants of arm and `riscv64`

Build for more platforms

---

.github/workflows/lint.yml

Use explicit Go version (defined in the `go.mod` file) to run Go linter workflow (GitHub Action - ActionLint). This way we will avoid current dependency issues on Go 1.24.
PR fixes this deps:
```
run golangci-lint
Running [/home/runner/golangci-lint-1.63.4-linux-amd64/golangci-lint run] in [/home/runner/work/nginx-prometheus-exporter/nginx-prometheus-exporter] ...
Error: ../../../go/pkg/mod/golang.org/x/sys@v0.29.0/unix/vgetrandom_linux.go:7:9: file requires newer Go version go1.24 (application built with go1.23) (typecheck)
package unix
^
Error: ../../../go/pkg/mod/golang.org/x/net@v0.34.0/http2/config_go124.go:7:9: file requires newer Go version go1.24 (application built with go1.23) (typecheck)
package http2
^
Error: issues found
Ran golangci-lint in 23318ms
```
Before creating a PR, …

Use Go version defined in go.mod for running Go linter action

---

go.mod

Closes #1047
Updates the main go version to 1.24.2 as well
If this project is used as a dependency, we need to validate that the go version bump does not interfere with other projects' functionality.

Update go.mod to use Go 1.24.2

---

.github/workflows/lint.yml
.golangci.yml
.pre-commit-config.yaml
Makefile
exporter.go
exporter_test.go

Merges these two PRs into one: #1029 #1028 
Neither can go in without the other one.

cherry-pick: golangci-lint version and action update

---

exporter.go

Address lint issue
```
Error: exporter.go:234:19: net.Dial must not be called. use (*net.Dialer).DialContext (noctx)
return net.Dial("unix", socketPath)
```

Switch to DialContext() to address lint issue

---

README.md
exporter.go
go.mod
go.sum

This PR introduces support for [proxy protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) v2 which is [available in nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/) starting from versions 1.13.11 (foss) and R16 (NGINX Plus).
Primary use case is running nginx-prometheus-exporter alongside with nginx or NGINX Plus sitting behind other load balancers like AWS [NLB](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html) or Google's [PNLB](https://cloud.google.com/load-balancing/docs/proxy-network-load-balancer) with proxy protocol enabled. Sometimes creating dedicated listeners just for [stub_status](nginx.org/r/stub_status) or [API](nginx.org/r/api) could be undesired, and with the proposed changes the …

Add proxy protocol v2 client-side support
