.travis.yml
README.md

Running fossa client on each push to verify licenses are ok
We use travis as CI/CD tool to run the job.

Add license scan with fossa and travis

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

* Added issue template
* Added pull request template
* Added contributing guide

Add Contributing Documentation 

---

.travis.yml
README.md

Travis will test and build a docker container that includes the binary.
The build passes if tests and docker build finish without error.

Run go test & build binary and container with travis

---

README.md

The go report badge will appear in the README file

Add go report badge in README file

---

README.md

Fix docker run command for NGINX OSS. Reported in https://github.com/nginxinc/nginx-prometheus-exporter/issues/8

Fix docker run command in README for NGINX

---

collector/nginx_plus.go
exporter.go
glide.lock
glide.yaml
vendor/github.com/nginxinc/nginx-plus-go-sdk/.github/ISSUE_TEMPLATE/bug_report.md
vendor/github.com/nginxinc/nginx-plus-go-sdk/.github/ISSUE_TEMPLATE/feature_request.md
vendor/github.com/nginxinc/nginx-plus-go-sdk/.github/PULL_REQUEST_TEMPLATE.md
vendor/github.com/nginxinc/nginx-plus-go-sdk/.gitignore
vendor/github.com/nginxinc/nginx-plus-go-sdk/CHANGELOG.md
vendor/github.com/nginxinc/nginx-plus-go-sdk/CONTRIBUTING.md
vendor/github.com/nginxinc/nginx-plus-go-sdk/LICENSE
vendor/github.com/nginxinc/nginx-plus-go-sdk/Makefile
vendor/github.com/nginxinc/nginx-plus-go-sdk/README.md
vendor/github.com/nginxinc/nginx-plus-go-sdk/client/nginx.go
vendor/github.com/nginxinc/nginx-plus-go-sdk/client/nginx_test.go
vendor/github.com/nginxinc/nginx-plus-go-sdk/docker/Dockerfile
vendor/github.com/nginxinc/nginx-plus-go-sdk/docker/nginx.conf
vendor/github.com/nginxinc/nginx-plus-go-sdk/docker/nginx_no_stream.conf
vendor/github.com/nginxinc/nginx-plus-go-sdk/docker/test.conf
vendor/github.com/nginxinc/nginx-plus-go-sdk/tests/client_no_stream_test.go
vendor/github.com/nginxinc/nginx-plus-go-sdk/tests/client_test.go

Replaces the embedded NGINX Plus client with the client from NGINX Plus go sdk -- https://github.com/nginxinc/nginx-plus-go-sdk 
The client from SDK includes stream server zone and stream usptream metrics, which are necessary for supporting stream related metrics in the exporter.

Use nginx plus go sdk

---

.travis.yml
Dockerfile

Update go version to 1.11 in the travis pipeline and the Dockerfile.

Use go 1.11

---

CHANGELOG.md
Makefile
README.md

Release 0.2.0

---

CHANGELOG.md
Makefile
README.md

Release 0.3.0
Note: must be rebased after https://github.com/nginxinc/nginx-prometheus-exporter/pull/33 is merged.

Release 0.3.0

---

.travis.yml
Dockerfile

Use go 1.12

---

CONTRIBUTING.md
Makefile
exporter.go

Add a Makefile option to run go linter in dev.

Add lint option to Makefile and fix lint issues

---

CHANGELOG.md
Makefile
README.md

Release 0.4.0

---

CHANGELOG.md
Makefile
README.md

Release 0.4.1

---

go.mod
go.sum
vendor/github.com/nginxinc/nginx-plus-go-client/client/nginx.go
vendor/modules.txt

Update vendor of prometheus exporter

Update go-client to v0.5.0

---

CHANGELOG.md
Makefile
README.md

Release 0.5.0

---

CHANGELOG.md
Makefile
README.md
build/Dockerfile

Fixes: https://github.com/nginxinc/nginx-prometheus-exporter/issues/82
* Release `0.6.0`.

Release 0.6.0

---

CHANGELOG.md
Makefile
README.md

Release 0.7.0

---

.github/workflows/ci.yml
build/ci/Jenkinsfile

Migrate continuous integration pipeline to Github actions.

Migrate to GitHub Actions

---

README.md

Fixes broken link to Dockerfile on README

docs: fix dockerfile link

---

.github/workflows/ci.yml

Add additional release condition to the workflow file.

Add conditional for release

---

CHANGELOG.md
Makefile
README.md

Release 0.8.0

---

.github/workflows/ci.yml

Fix release condition to allow Docker push from pipeline when a tag is created.

Fix release condition

---

.github/workflows/ci.yml

Switch to default Docker registry for Github Action.

Switch to default registry

---

.github/workflows/ci.yml

Add internal Slack notifications for failed builds.

Add Slack notification for failed builds

---

.travis.yml
build/Dockerfile
go.mod

Update Go version to 1.15

---

.github/workflows/ci.yml

Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

Update Slack notifications

---

.github/workflows/lint.yml
Makefile

Add lint workflow

---

.github/workflows/ci.yml
.github/workflows/fossa.yml
.github/workflows/lint.yml

Add exclusion for docs / examples changes

Add exclusion for docs / examples changes

---

.github/workflows/ci.yml
.github/workflows/fossa.yml

Update workflow status version

Update workflow status version

---

collector/nginx_plus.go

These need to be added to fix errors in https://github.com/nginxinc/kubernetes-ingress/pull/1233

Add function names to struct description

---

collector/nginx_plus.go
exporter.go

This fixes bugs introduced in https://github.com/nginxinc/nginx-prometheus-exporter/commit/1ffb988ca6f9972fc17cdb64cf35e4e92132a28d

Fix bugs in exporter

---

.github/workflows/stale.yml

Add GitHub workflow to check for stale PRs and issues

---

.github/workflows/ci.yml
.github/workflows/fossa.yml
build/Dockerfile
go.mod

Update Go version to 1.16

---

Makefile
build/Dockerfile

Add date to binary when building locally

---

CHANGELOG.md
Makefile
README.md

Release 0.9.0

---

.github/workflows/ci.yml

Fix release order

---

.github/release-drafter.yml

Move dependencies into separate category

---

collector/nginx_plus.go

Fix upstream server fails metric description

---

.github/workflows/ci.yml

- Setup Golang environment in every job
- Setup QEMU
- Add parameter to checkout

Add setups for Golang and QEMU

---

README.md

* Add documentation for each metric
* Change urls to `https` protocol instead of `http` where appropriate.

Add documentation for metrics

---

client/nginx.go
client/nginx_test.go

Simple visual templating Nginx for parsing metrics.

Simple parsing nginx metrics [parseStubStats]

---

.github/workflows/ci.yml

Upload Docker images to GitHub Container Registry

Upload Docker images to GHCR

---

.github/workflows/ci.yml

Removing nightly for now as it's a little bit overkill since we don't have that many changes a day.

Remove nightly build for now

---

.github/workflows/ci.yml
build/Dockerfile

Adding more info to the labels.

Add more labels to Docker image

---

.github/workflows/ci.yml

Start pushing images to https://gallery.ecr.aws/nginx/nginx-prometheus-exporter

Upload Docker images to AWS ECR Public

---

.github/release-drafter.yml
README.md

Adding documentation for the new registries.

Add docs for GHCR and AWS ECR

---

.github/release-drafter.yml
.goreleaser.yml
Makefile
README.md

Adds step to publish a Homebrew formula.

Add Homebrew tap

---

.goreleaser.yml

Adds binaries for Windows for 386, amd64 and arm64

Add binaries for Windows

---

CHANGELOG.md
Makefile
README.md

Release 0.10.0

---

.github/workflows/notifications.yml

Uses https://github.com/actions/github-script to get data from the API.

Use actions/github-script to get data for notifications

---

go.mod

Bump Go to 1.18

---

.github/workflows/ci.yml
.goreleaser.yml

Adds SBOMs for all the published artifacts.

Add SBOMs to release

---

.github/workflows/ci.yml
.goreleaser.yml

This will send a message to the `#announcements` channel on release.

Add Slack announcement to nginxcommunity

---

go.mod

Bump Go to 1.19

---

.goreleaser.yml
CHANGELOG.md
Makefile

Release 0.11.0

---

.github/workflows/scorecards.yml

Looks like Dependabot wasn't updating some of the actions. This PR updates them and adds comments with the version where missing.

Update Scorecards workflow

---

build/Dockerfile

https://go.dev/blog/go1.20
Signed-off-by: Kevin Kirsche <kev.kirsche@gmail.com>
Update Golang version from 1.19 to 1.20
The motivation for this is to ensure that if changes such as the RNG are

Update Dockerfile Go version from 1.19 to 1.20

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
.markdownlint-cli2.yaml
.pre-commit-config.yaml
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
ISSUE_LIFECYCLE.md
README.md
SECURITY.md
grafana/README.md

Add linting for markdown files

---

.github/workflows/codeql-analysis.yml
build/Dockerfile
go.mod
go.sum

Bump Go to 1.21.3

---

.github/workflows/ci.yml

Add annotations to Docker image

---

exporter.go

Restore `SCRAPE_URI` that was removed in #420 by mistake
Fixes #585

Restore SCRAPE_URI env var

---

.github/workflows/ci.yml
.goreleaser.yml

Adds configuration to create [Nix packages](https://github.com/NixOS/nixpkgs)

Add config to publish Nix packages

---

.github/workflows/ci.yml
.goreleaser.yml

Adds configuration for https://scoop.sh/

Add config to publish scoop packages

---

.goreleaser.yml

Adds commit author when pushing to the scoop repo.

Add commit author for Scoop

---

examples/kubernetes/README.md
examples/kubernetes/nginx-hello.yaml

Add k8s example

---

.codecov.yml
.github/workflows/ci.yml
.gitignore
Makefile
README.md

Add Codecov

---

.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml

Updates the workflow with the latest changes

Update CodeQL workflow

---

.pre-commit-config.yaml
.yamllint.yaml

We use renovate now to keep it up to date and there's no way to disable pre-commit.

Update pre-commit schedule

---

README.md

Replace link from NGINX community slack with community forum.
Closes #1044

docs: Update Readme for community support link

---

go.mod

Update go version to 1.25.0

---

Makefile
README.md

Release 1.5.0
